/*
 * ILI9341.c
 *
 *  Created on: 6 авг. 2023 г.
 *      Author: AnastasII
 */
#include "ILI9341.h"
#include <IRQ.h>
#define CS_ON	GPIOA->BSRR |= GPIO_BSRR_BR9;
#define CS_OFF	GPIOA->BSRR |= GPIO_BSRR_BS9;

#define RSx_ON	GPIOA->BSRR |= GPIO_BSRR_BR8;
#define RSx_OFF	GPIOA->BSRR |= GPIO_BSRR_BS8;

#define WR_ON	GPIOB->BSRR |= GPIO_BSRR_BR10;
#define WR_OFF	GPIOB->BSRR |= GPIO_BSRR_BS10;

#define RST_ON	GPIOA->BSRR |= GPIO_BSRR_BR10;
#define RST_OFF	GPIOA->BSRR |= GPIO_BSRR_BS10;

D_ARR	D	=	D_DEFAULT;

void GPIO_Init(){
	//RCC
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;

	//GPIO
	/* D[0:7] => 0
	 * D0	->	PB0
	 * D1	->	PB1
	 * D2	->	PA2
	 * D3	->	PA3
	 * D4	->	PA4
	 * D5	->	PA5
	 * D6	->	PA6
	 * D7	->	PA7	*/
	//D0
	GPIOB->CRL |= GPIO_CRL_MODE0;
	GPIOB->CRL &= ~GPIO_CRL_CNF0;
	GPIOB->BSRR |= GPIO_BSRR_BR0;
	//D1
	GPIOB->CRL |= GPIO_CRL_MODE1;
	GPIOB->CRL &= ~GPIO_CRL_CNF1;
	GPIOB->BSRR |= GPIO_BSRR_BR1;
	//D2
	GPIOA->CRL |= GPIO_CRL_MODE2;
	GPIOA->CRL &= ~GPIO_CRL_CNF2;
	GPIOA->BSRR |= GPIO_BSRR_BR2;
	//D3
	GPIOA->CRL |= GPIO_CRL_MODE3;
	GPIOA->CRL &= ~GPIO_CRL_CNF3;
	GPIOA->BSRR |= GPIO_BSRR_BR3;
	//D4
	GPIOA->CRL |= GPIO_CRL_MODE4;
	GPIOA->CRL &= ~GPIO_CRL_CNF4;
	GPIOA->BSRR |= GPIO_BSRR_BR4;
	//D5
	GPIOA->CRL |= GPIO_CRL_MODE5;
	GPIOA->CRL &= ~GPIO_CRL_CNF5;
	GPIOA->BSRR |= GPIO_BSRR_BR5;
	//D6
	GPIOA->CRL |= GPIO_CRL_MODE6;
	GPIOA->CRL &= ~GPIO_CRL_CNF6;
	GPIOA->BSRR |= GPIO_BSRR_BR6;
	//D7
	GPIOA->CRL |= GPIO_CRL_MODE7;
	GPIOA->CRL &= ~GPIO_CRL_CNF7;
	GPIOA->BSRR |= GPIO_BSRR_BR7;

	/* WR/RD => 1
	 * WRx	->	PB10
	 * RDx	->	PB11 */
	//WRx
	GPIOB->CRH |= GPIO_CRH_MODE10;
	GPIOB->CRH &= ~GPIO_CRH_CNF10;
	GPIOB->BSRR |= GPIO_BSRR_BS10;
	//RDx
	GPIOB->CRH |= GPIO_CRH_MODE11;
	GPIOB->CRH &= ~GPIO_CRH_CNF11;
	GPIOB->BSRR |= GPIO_BSRR_BS11;

	/* RSx/CS =>
	 * RSx	->	PA8
	 * CS	->	PA9
	 * RST	->	PA10*/
	//RSx
	GPIOA->CRH |= GPIO_CRH_MODE8;
	GPIOA->CRH &= ~GPIO_CRH_CNF8;
	GPIOA->BSRR |= GPIO_BSRR_BS8;
	//CS
	GPIOA->CRH |= GPIO_CRH_MODE9;
	GPIOA->CRH &= ~GPIO_CRH_CNF9;
	GPIOA->BSRR |= GPIO_BSRR_BS9;
	//RST
	GPIOA->CRH |= GPIO_CRH_MODE10;
	GPIOA->CRH &= ~GPIO_CRH_CNF10;
	GPIOA->BSRR |= GPIO_BSRR_BS10;
}

void Send_Command(uint8_t command){
	D.all = command;

	if(D.bit.D_7){
		GPIOA->BSRR |= GPIO_BSRR_BS7;
		GPIOA->BSRR |= GPIO_BSRR_BR7;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR7;

	if(D.bit.D_6){
		GPIOA->BSRR |= GPIO_BSRR_BS6;
		GPIOA->BSRR |= GPIO_BSRR_BR6;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR6;

	if(D.bit.D_5){
		GPIOA->BSRR |= GPIO_BSRR_BS5;
		GPIOA->BSRR |= GPIO_BSRR_BR5;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR5;

	if(D.bit.D_4){
		GPIOA->BSRR |= GPIO_BSRR_BS4;
		GPIOA->BSRR |= GPIO_BSRR_BR4;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR4;

	if(D.bit.D_3){
		GPIOA->BSRR |= GPIO_BSRR_BS3;
		GPIOA->BSRR |= GPIO_BSRR_BR3;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR3;


	if(D.bit.D_2){
		GPIOA->BSRR |= GPIO_BSRR_BS2;
		GPIOA->BSRR |= GPIO_BSRR_BR2;
	}
	else
		GPIOA->BSRR |= GPIO_BSRR_BR2;

	if(D.bit.D_1){
		GPIOB->BSRR |= GPIO_BSRR_BS1;
		GPIOB->BSRR |= GPIO_BSRR_BR1;
	}
	else
		GPIOB->BSRR |= GPIO_BSRR_BR1;

	if(D.bit.D_0){
		GPIOB->BSRR |= GPIO_BSRR_BS0;
		GPIOB->BSRR |= GPIO_BSRR_BR0;
	}
	else
		GPIOB->BSRR |= GPIO_BSRR_BR0;

}
void ILI_Reset(uint32_t cmd){
	CS_ON;
	RSx_ON;
	WR_ON;
	RST_ON;
	delay_time(125);
	//Send_Command(cmd);
	WR_OFF;
	RSx_OFF;
	CS_OFF;
}

void ILI_9341_init(){
	GPIO_Init();

	ILI_Reset(0x10);
}



